[package]
name = "c-le-videosr"
version = "0.1.0"
description = "Local-first AI video enhancement workstation"
authors = ["C.le."]
edition = "2021"

[lib]
name = "c_le_videosr_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.37"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
thiserror = "2"
window-vibrancy = "0.7"
