export function bi(zh: string, en: string) {
  return `${zh} / ${en}`;
}

export const ui = {
  unknown: bi("未知", "Unknown"),
  localProcessing: bi("本地处理", "Local processing"),
  selectVideo: bi("选择视频", "Select video"),
  chooseAnother: bi("选择其他视频", "Choose another video"),
  inspecting: bi("正在分析…", "Inspecting…"),
  ffprobeMissing: bi("未检测到 ffprobe，请配置托管运行时或 PATH。", "ffprobe is not available in the managed runtime or PATH."),
  srTarget: bi("超分目标", "SR target"),
  readyAi: bi("本地 AI 已就绪", "Ready for local AI processing"),
  mediaReadyAiMissing: bi("媒体管线已就绪 · AI 运行时或模型缺失", "Media pipeline ready · AI runtime or model missing"),
  enhancementMode: bi("增强模式", "Enhancement mode"),
  engineAware: bi("引擎感知", "Engine-aware"),
  enhancement: bi("增强设置", "Enhancement"),
  plannedBackend: bi("后端规划中", "Planned backend"),
  superResolution: bi("超分辨率", "Super resolution"),
  upscaleModel: bi("超分模型", "Upscale model"),
  noUpscaleProfiles: bi("没有可用的极速超分模型", "No runnable Fast-mode upscale profiles"),
  frameInterpolation: bi("视频补帧", "Frame interpolation"),
  rifeModel: bi("RIFE 模型", "RIFE model"),
  noRifeProfiles: bi("没有可用的 RIFE 模型", "No runnable RIFE profiles"),
  targetFps: bi("目标帧率", "Target FPS"),
  sceneProtection: bi("场景保护 · 阈值 0.42 · 单帧重叠", "Scene protection · 0.42 threshold · one-frame overlap"),
  videoCodec: bi("视频编码", "Video codec"),
  copyM1: bi("复制源视频流 · 仅 M1", "Copy source video stream · M1 only"),
  chooseOutput: bi("选择输出文件", "Choose output file"),
  cancelProcessing: bi("取消处理", "Cancel processing"),
  enhanceVideo: bi("视频增强", "Enhance video"),
  interpolateVideo: bi("视频补帧", "Interpolate video"),
  validatePipeline: bi("验证媒体管线", "Validate media pipeline"),
  ffmpegRequired: bi("视频处理需要 FFmpeg。", "FFmpeg is required for video processing."),
  rifeMissing: bi("RIFE 运行时不可用，补帧已禁用。", "RIFE runtime is not available, so frame interpolation is disabled."),
  aiCopyUnsupported: bi("AI 会生成新视频帧，请选择 H.264 或 H.265，不能使用流复制。", "AI transforms create new video frames, so H.264 or H.265 must be selected instead of stream copy."),
  plannedModes: bi("Quality 与 AI Restore 暂时禁用，等待对应运行时接入。", "Quality and AI Restore remain disabled until their runtimes land."),
  fastPipeline: bi("极速模式使用有界帧分块，并为每个任务保持单一持久编码器。", "Fast mode uses bounded frame chunks and one persistent encoder per job."),
  source: bi("源媒体", "Source"),
  video: bi("视频", "Video"),
  audio: bi("音频", "Audio"),
  container: bi("容器", "Container"),
  frameTiming: bi("帧时间轴", "Frame timing"),
  colorDepth: bi("色彩 / 位深", "Color / bit depth"),
  auxiliaryStreams: bi("字幕 / 附件", "Subtitles / attachments"),
  mediaRuntime: bi("媒体运行时", "Media runtime"),
  ready: bi("就绪", "Ready"),
  unavailable: bi("不可用", "Unavailable"),
  detected: bi("已检测", "Detected"),
  missing: bi("缺失", "Missing"),
  aiRuntime: bi("AI 运行时", "AI runtime"),
  models: bi("模型", "Models"),
  catalog: bi("模型目录", "Catalog"),
  managedDirectory: bi("托管模型目录", "Managed directory"),
  modelNotStaged: bi("未部署模型载荷", "Model payload not staged"),
  loading: bi("加载中", "Loading"),
  system: bi("系统", "System"),
  checking: bi("检测中", "Checking"),
  platform: bi("平台", "Platform"),
  memory: bi("内存", "Memory"),
  gpuAuto: bi("NCNN 将自动选择 Vulkan GPU", "NCNN will select a Vulkan GPU automatically"),
  readingCapabilities: bi("正在读取本机能力…", "Reading local capabilities…"),
  processed: bi("已处理", "processed"),
  vfrBlocked: bi("检测到可变帧率（VFR）。当前 AI 管线为避免时间戳漂移会阻止处理。", "Variable frame rate detected. AI processing is blocked until timestamp-preserving VFR support lands."),
  hdrBlocked: bi("检测到 HDR 或高位深视频。当前 8-bit AI 编码链会造成质量损失，因此已阻止处理。", "HDR or high-bit-depth video detected. The current 8-bit AI encoder path is blocked to prevent silent quality loss."),
  interlacedBlocked: bi("检测到隔行扫描视频，请先去交错。", "Interlaced video detected; deinterlace it before AI processing."),
  mkvSubtitleHint: bi("源文件包含字幕或附件。选择 MKV 输出可无损复制这些流与章节。", "The source contains subtitles or attachments. Choose MKV to copy those streams and chapters without conversion."),
  mp4SubtitleWarning: bi("MP4 输出会保留章节，但当前不会复制源字幕/附件；如需保留请改用 MKV。", "MP4 keeps chapters but currently omits source subtitles/attachments; choose MKV to preserve them."),
  inactiveJob: bi("处理任务已不再运行。", "The processing job is no longer active."),
  cancelling: bi("正在取消…", "Cancelling…"),
};
